ALTER TABLE ingredient ALTER COLUMN category TYPE VARCHAR;
ALTER TABLE ingredient ALTER COLUMN measure TYPE VARCHAR;
ALTER TABLE ingredient ALTER COLUMN name TYPE VARCHAR;
ALTER TABLE ingredient ALTER COLUMN text TYPE VARCHAR;
ALTER TABLE recipe ALTER COLUMN label TYPE VARCHAR;